# Generated by Django 2.0.3 on 2018-03-20 07:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180320_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='response_card',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), blank=True, null=True, size=25),
        ),
    ]
